name: Translate Content

on:
  push:
    branches: [main]
    paths:
      - 'content/en/**'  # Trigger only when changes occur in the source directory

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Translation Action
        uses: ./.github/actions/translate-content
        with:
          token: ${{ secrets.Action }}
          langs: "es"

      - name: List Github Actions Directory
        run: |
          ls -R .github/actions/
